greeting:
  message: "hello"

quarkus:
  http:
    cors:
      enabled: true
      origins:
        - "http://localhost:4200"
  mongodb:
    connection-string: mongodb://localhost:27017
    database: thesis